packages:
  - packages/*
  - scripts

catalogMode: prefer

catalog:
  "@types/node": ^24
  "@vitest/coverage-v8": 4.1.11
  jiti: ^2.7.0
  memfs: ^4.69.1
  neverthrow: ^8.2.0
  node-html-parser: ^9.0.3
  typescript: ^7.0.2
  valibot: ^1.4.2
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
