name: coverage-reporter
on:
  workflow_run:
    workflows:
      - coverage
    types:
      - completed

jobs:
  on-complete:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      actions: read

    steps:
      - name: download
        uses: actions/download-artifact@v8
        with:
          name: coverage
          path: .kiso-ci/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
      - name: temp
        run: cat .kiso-ci/test-result.json
